### PR TITLE
nico/polymer proofs

### PR DESCRIPTION
**Pull request by nicopernas**
This PR adds proof support to the vibc-core sc. Specifically to these operations
- update optimistic consensus state (update app hash)
- channel handshake
- receive packet and ack. 

Things that are not covered yet
- timeouts
- closing channels

There's some changes to the channel handshake API since we were missing information required to verify the provided proofs. Although these changes are minimal to make the releyer dev a bit easier. We will have to do a proper clean up later 

To verify that everything is running as expected, run `forge test`

## Summary by CodeRabbit

- **New Features**
    - Added support for Optimism and Base64 as submodules.
    - Introduced new contracts for managing consensus states and verifying proofs in Optimistic environments.
    - Enhanced IBC (Inter-Blockchain Communication) functionality with new states, utility functions, and improved proof verification.
    - Implemented Protocol Buffers for efficient data encoding and decoding within contracts.
    - Added automated Solidity code generation from protobuf files.
- **Enhancements**
    - Streamlined contract functions for creating and updating clients, opening and connecting IBC channels.
    - Consolidated counterparty information into a single struct for better readability and efficiency.
- **Bug Fixes**
    - Addressed issues related to packet acknowledgment and commitment proof verification.
- **Documentation**
    - Improved inline documentation and added new test scripts for contract interaction and verification.
- **Refactor**
    - Significant codebase restructuring and simplification across multiple contracts for clarity and performance.
- **Tests**
    - Expanded testing suite with new tests for dispatcher operations, proof verification, and IBC channel management.

### CODE REVIEW

**Comment by dshiell** [comment]
Should we add the external solidity dependencies like RLPReader.sol as submodules instead of copying them into our code base?

**Comment by dshiell** [comment]
@coderabbitai review

**Comment by nicopernas** [comment]
> Should we add the external solidity dependencies like RLPReader.sol as submodules instead of copying them into our code base?

yeah! that was there because I was just lazy

**Comment by dshiell** [comment]
@coderabbitai review

**Pull request merged**
